### ISSUE TITLE
Error creating new project - cannot find module 'ms'

### ISSUE THREAD

**Issue by thiagomeireless** [AdonisCommunity/create-adonis-ts-app#11]
## Package version

1.3.6

## Node.js and npm version

❯ node -v
v12.16.1
❯ npm -v
6.14.4
❯ yarn -v
1.22.4

I'm also using `nvm`:
❯ nvm --version
0.35.3

## Sample Code (to reproduce the issue)

```
❯ npx create-adonis-ts-app hello-world
npx: installed 129 in 7.306s
Cannot find module 'ms'
Require stack:
- /home/thiago/.npm/_npx/155699/lib/node_modules/create-adonis-ts-app/node_modules/@poppinss/utils/build/src/MessageBuilder.js
- /home/thiago/.npm/_npx/155699/lib/node_modules/create-adonis-ts-app/node_modules/@poppinss/utils/build/index.js
- /home/thiago/.npm/_npx/155699/lib/node_modules/create-adonis-ts-app/node_modules/@adonisjs/sink/src/executeInstructions.js
- /home/thiago/.npm/_npx/155699/lib/node_modules/create-adonis-ts-app/node_modules/@adonisjs/sink/index.js
- /home/thiago/.npm/_npx/155699/lib/node_modules/create-adonis-ts-app/build/index.js
- /home/thiago/.npm/_npx/155699/lib/node_modules/create-adonis-ts-app/build/bin/run.js
```

```
❯ yarn create adonis-ts-app hello-world
yarn create v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "create-adonis-ts-app > @adonisjs/application@1.3.10" has unmet peer dependency "@adonisjs/fold@^6.0.0".
[4/4] Building fresh packages...
success Installed "create-adonis-ts-app@1.3.6" with binaries:
      - create-adonis-ts-app
[#################################################################################################################################] 129/129internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'ms'
Require stack:
- /home/thiago/.config/yarn/global/node_modules/@poppinss/utils/build/src/MessageBuilder.js
- /home/thiago/.config/yarn/global/node_modules/@poppinss/utils/build/index.js
- /home/thiago/.config/yarn/global/node_modules/@adonisjs/sink/src/executeInstructions.js
- /home/thiago/.config/yarn/global/node_modules/@adonisjs/sink/index.js
- /home/thiago/.config/yarn/global/node_modules/create-adonis-ts-app/build/index.js
- /home/thiago/.config/yarn/global/node_modules/create-adonis-ts-app/build/bin/run.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/thiago/.config/yarn/global/node_modules/@poppinss/utils/build/src/MessageBuilder.js:14:30)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/thiago/.config/yarn/global/node_modules/@poppinss/utils/build/src/MessageBuilder.js',
    '/home/thiago/.config/yarn/global/node_modules/@poppinss/utils/build/index.js',
    '/home/thiago/.config/yarn/global/node_modules/@adonisjs/sink/src/executeInstructions.js',
    '/home/thiago/.config/yarn/global/node_modules/@adonisjs/sink/index.js',
    '/home/thiago/.config/yarn/global/node_modules/create-adonis-ts-app/build/index.js',
    '/home/thiago/.config/yarn/global/node_modules/create-adonis-ts-app/build/bin/run.js'
  ]
}
error Command failed.
Exit code: 1
Command: /home/thiago/.yarn/bin/create-adonis-ts-app
Arguments: hello-world
Directory: /home/thiago/Projetos
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

## BONUS (a sample repo to reproduce the issue)

Tried running `npm cache clean --force` before the commands, without success.

Also tried with node v13 just in case, without success.

Also tried `npx create-adonis-ts-app@v1.3.5 hello-world` without success.

**Comment by RomainLanz** [comment]
Hey @thiagomeireless! 👋 

May you try to run the **npx** command with the flag `--ignore-existing`?

```bash
> npx --ignore-existing create-adonis-ts-app hello-world
```

**Comment by thiagomeireless** [comment]
Worked perfectly with the flag! Thank you again for the quick support.
