### ISSUE TITLE
Error running npx command

### ISSUE THREAD

**Issue by DrummerSi** [AdonisCommunity/create-adonis-ts-app#4]
Received the following error when running the installation command on both Windows and linux systems:

 ``` 
TypeError: Cannot read property 'update' of undefined
        at instructions (/mnt/d/Repos/yardstick/node_modules/@adonisjs/view/build/instructions.js:7:12)
        at Object.executeInstructions (/mnt/c/Users/Simon/AppData/Local/Yarn/Data/global/node_modules/@adonisjs/sink/src/executeInstructions.js:23:15)
        at processTicksAndRejections (internal/process/task_queues.js:86:5) 
```

I guess Adonis updated something?

**Comment by RomainLanz** [comment]
Hey @DrummerSi!

This shouldn't be used yet.
Closing.
