### ISSUE TITLE
Unable to create a new project using npx

### ISSUE THREAD

**Issue by webNeat** [AdonisCommunity/create-adonis-ts-app#7]
Hello,
First of all, I want to thank you for the amazing work you are doing in this framework.
I wanted to start testing the new version, but couldn't create a new project using `npx` (creating it using `yarn` went just fine).

## Package version
1.3.5

## Node.js and npm version
Node: 12.16.1
npm: 6.12.1

## Sample Code (to reproduce the issue)
![adonis](https://user-images.githubusercontent.com/2133333/76681631-65f26a00-65f5-11ea-8003-d2900d5e856a.png)

```
   TypeError: Cannot read property 'create' of undefined 
        at instructions (/home/webneat/workspace/personal/blog/node_modules/@adonisjs/core/build/instructions.js:26:16)
        at Object.executeInstructions (/usr/lib/node_modules/create-adonis-ts-app/node_modules/@adonisjs/sink/src/executeInstructions.js:15:11)
        at task (/usr/lib/node_modules/create-adonis-ts-app/build/tasks/executeInstructions.js:7:22)
        at Object.runTasks (/usr/lib/node_modules/create-adonis-ts-app/build/index.js:30:19)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)

   Unable to create new project. Rolling back
```

**Comment by thetutlage** [comment]
Closing, since this is not an issue anymore. Around March we were just trying to assemble things and hence this package had a lot of weird bugs.
