### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by jericopulvera** [AdonisCommunity/create-adonis-ts-app#9]
## Package version
npm ├─┬ create-adonis-ts-app@1.3.5

## Node.js and npm version
v12.16.1 and v6.13.4

## Sample Code (to reproduce the issue)
npx create-adonis-ts-app blog 

## Output
```
➜ npx create-adonis-ts-app adonis-mongoose-boilerplate
npx: installed 107 in 11.474s
    _       _             _         _     
   / \   __| | ___  _ __ (_)___    | |___ 
  / _ \ / _` |/ _ \| '_ \| / __|_  | / __|
 / ___ \ (_| | (_) | | | | \__ \ |_| \__ \
/_/   \_\__,_|\___/|_| |_|_|___/\___/|___/

✔ Select the project structure · api
✔ Enter the project name · blog
✔ Setup eslint? (y/N) · true
   create    .adonisrc.json
   create    .env, .env.example
   create    .gitignore
   create    tsconfig.json
   create    .eslintrc.json, .eslintignore
   create    ace
   create    app/Exceptions/Handler.ts
   create    commands/index.ts
   create    providers/AppProvider.ts
   create    server.ts
   create    start/kernel.ts
   create    start/routes.ts
   create    .editorconfig
   install   typescript, @adonisjs/assembler, eslint, eslint-plugin-adonis, youch, youch-terminal, pino-pretty, and 1 other [dev]
   install   @adonisjs/core, @adonisjs/ace, @adonisjs/fold, reflect-metadata, proxy-addr, source-map-support [prod]
   fatal     npm ERR! Unexpected end of JSON input while parsing near '...odule-name":"^2.1.0",'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eco/.npm/_logs/2020-03-23T13_36_35_131Z-debug.log

   error     Unable to create new project. Rolling back
   fatal     Error: Installation failed
    at task (/Users/eco/.npm/_npx/3184/lib/node_modules/create-adonis-ts-app/build/tasks/createPackageFile.js:82:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.runTasks (/Users/eco/.npm/_npx/3184/lib/node_modules/create-adonis-ts-app/build/index.js:138:13)

```

**Comment by jericopulvera** [comment]
npm cache clean --force

fixed my problem. 
https://github.com/vuejs-templates/webpack/issues/990
